#!/bin/bash

last_rebase_hash=$(git reflog --grep-reflog="rebase" --pretty=format:"%h" -n 1)
last_commit_hash=$(git rev-parse --verify HEAD)
commits_after_rebase=$(git log $last_rebase_hash..$last_commit_hash --pretty=oneline | wc -l)


if [ "$last_rebase_hash" = "" ]
then
python2 /home/deadcrow2021/Desktop/git scrypt/write_file.py
python2 /home/deadcrow2021/Desktop/git scrypt/scrypt-new.py
GIT_SEQUENCE_EDITOR='cat git-rebase-todo >' git rebase -i --keep-empty --allow-empty-message --root master

else
	if [ "$commits_after_rebase" > 20 ]
	then
	python2 /home/deadcrow2021/Desktop/git scrypt/write_file.py -n $commits_after_rebase
	python2 /home/deadcrow2021/Desktop/git scrypt/scrypt-new.py
	GIT_SEQUENCE_EDITOR='cat git-rebase-todo >' git rebase -i --keep-empty --allow-empty-message HEAD~$commits_after_rebase master
fi

